-- TODOS LOS CODIGOS O CUNSULTAS INTEREANTES O PENSAMIENTOS DE PROCEDIMIENTO O DE VIDA LOS VAMOS A ALMACENAS ACA , CON UNA BREBE DESCRIPCION DE LO QUE PUEDE HACER Y COMO EMPLEARLO, ACOMPA;ADO DE LA EPIFANIA QUE SALIO DEL MOMENTO.

